config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get ':fakr', to: 'links#show', as: 'fakr'

  root to: 'links#index'

  
  get '/users/new', to: 'users#new'
  post '/users', to: 'users#create'

  get 'links', to: 'link#show'
  get 'links/new', to: 'link#new'
  post 'links', to: 'link#create'
  get 'link/:id', to: 'link#page', as: 'link_id'
  
  get 'links/:id/comments', to: 'link/comments#show'
  get 'link/:id/comment/new', to: 'link/comments#new'
  post 'comments', to: 'comments#create'
  get 'link/:id/comments/edit', to: 'comments#edit', as: 'comments_edit'
  get 'link/:id/comment', to: 'link/comments#page', as: 'comment'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
end

app/models/link.rb
class Link < ActiveRecord::Base
  has_many :comments
  has_many :votes
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :links
  has_many :comments
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :update]

  def show
    @link = Link.find(params[:id])
    #@comments = Comment.where(link_id: @link.id)
    @comments = @link.comments
    @action = comments_path
    @http_verb = :post
    render :show
  end

  # POST /link/:id/comments
  def create
    if session[:user_id]
      @link = Link.find(params[:id])
      @comment = @link.comments.create(content: params[:content],
                                       user_id: session[:user_id])
    else
      flash[:alert] = "Piss off."
    end
    redirect_to link_id_path(@link)
  end

end

app/controllers/link_controller.rb
class LinksController < ApplicationController
  
  def create
    @link = Link.create(title: params[:title],
                        destination: params[:destination],
                        created_at: DateTime.now)
    redirect_to links_path
    # redirect_to post_path(@post)
  end

  def new
    @link = Link.new
    render :new
  end

  def show
    @links = Link.all
    render :index

  end



end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  before_action :authenticate_user!, only: [:create, :update]
  
  def create
    @link = Link.create(title: params[:title],
                        destination: params[:destination],
                        created_at: DateTime.now)
    redirect_to links_path
    # redirect_to post_path(@post)
  end

  def new
    @link = Link.new
    render :new
  end

  def show
    @links = Link.all
    render :index

  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @action = users_path
    render :new
  end

  def create
    passhash = Digest::SHA1.hexdigest(params[:password])
    @user = User.create(email: params[:email], password: passhash)
    flash[:notice] = "User successfully created"
    redirect_to :root
  end

  def index
    @users = User.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Fakr </title>
  <link href="<%= url('/application.css') %>" rel="stylesheet" type="text/css" />
</head>
<body>
<div class="container">
  
  <header>
    <div class="header">
      <nav class="navigationlinks">
        <a href="#">Comments</a>
        <a href="#">Related</a>
      </nav>
    </div>
  </header>
 
  <div class="userlink">
  
      <div class="link">
            
            <%= render partial: "link", locals: {link: @link } %>
   
        </div>
    </div>
      
      <br>
    
      <div>
        <h2>top 200 Comments</h2> <p>show 500</p>
        </div>
      
      <br>

      <div class="comments">

          <div class="new comments">

			<textarea>
            
	            <% content_for :comment_rule do %>
	             <% end %>
	              <%= render partial: "new", locals: { link_id: link } %>
		            <% end %>

		          </textarea>
				     
	        </div>

	    </div>
          

    <div class="side">
      <div class="spacer">
      <h3>Submit a Link</h3>
      </div>
    </div>
  </div>
</div>
</html>

<br/>
<div>
  <%= link_to "Back", :back %>
</div>

app/views/comments/_new.html.erb
<div class="comment-input">
  
  <% content_for :comments_rule do %>

    <ul>
        <li>REMEBER</li>
        <li> -- Be nice</li>
        <li> -- No bots</li>
        <li> -- No slurs or harrasing commnets</li>
        <li> -- No linking to personal social media pages</li>
        <li> -- No asking for donations (Try /r/Assistance)</li>

    <% end %>

  </div>

  <div class="comment-input">

    <%= render partial: "links", locals: { link: @link } %>
    <%= form_tag(post_comment_path) do %>
    <%= text_area_tag(:content) %>
    <%= link_to "Add New Comment", comments_new_path  %>
  </div>

  <br/>

  <div><%= submit_comment 'Save' %></div>

<% end %>

app/views/comments/show.html.erb
<%= render partial: "comment" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fakr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <header>
    <div class="row">
      <div class="col-md-8">
        <h1 class="logo">Faker</h1>
          <nav class="navigationlinks">
            <a href="#">Hot</a>
            <a href="#">New</a>
            <a href="#">Rising</a>
            <a href="#">Controversial</a>
            <a href="#">Top</a>
            <a href="#">Gilded</a>
            <a href="#">Wiki</a>
            <a href="#">Promoted</a>
          </nav>
      </div>
    <div class="col-md-4">
      <div class="side">
      <div class="spacer">
        <form class="form-inline">
         <input class="searchbar" type="text" placeholder="Search" required>
          <input class="searchbutton" type="button" value="Search">
        </form>
      </div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      <div class="form-group">
        <%= button_to "New User/Sign Up", users_new_path, :class => "button", :method => :get  %>
        <%= button_to "Login", users_new_path, :class => "button", :method => :get  %>
      </div>
    </div>
  </div>
  </header>


<%= yield %>

</body>
</html>

app/views/links/_links.html.erb
<div class="links">
  <h2><%= link_to_unless_current link.title, link_id_path(link) %></h2>
   <h3> Title: <%= link.title %></h3>
 
   <h4> Destination: <%= (link.destination) %></h4>
</div>

app/views/links/index.html.erb
    <div class="links">
      <% if @links %>
        <% @links.each do |link| %>
          <%= render partial: "links", locals: { link: link } %>
        <% end %>
      <% end %>
    </div>

app/views/links/new.html.erb
<h2>New Link</h2>

<% # Title, Tags, Text %>
<!-- Title, Tags, Text -->

<%= form_tag('/links/new', class: 'link-form') do %>
  <div class="link-input">
    <%= label_tag(:title, "Title: ") %>
    <%= text_field_tag(:title, nil, size: 40) %>
  </div>

  <div class="link-input">
    <%= label_tag(:destination, "Link URL: ") %>
    <%= text_field_tag(:destination, nil, size: 60) %>
  </div> 

  <br/>
  <div><%= submit_tag 'Upload link' %></div>
<% end %>

<br/>
<div>
  <%= link_to "Back", :back %>
</div>

app/views/users/_form.html.erb
<%= form_tag(@action, method: :post) do %>

  <div class="form-group">
    <%= label_tag(:email, "Email: ") %>
    <%= text_field_tag(:email, nil, size: 40) %>
  </div>

  <div class="form-group">
    <%= label_tag(:password, "Password: ") %>
    <%= password_field_tag(:password) %>
  </div>

  <%= submit_tag("Login/Sign Up") %>
  <br/>
  <div>
    <%= link_to "Back", :back %>
  </div>

<% end %>

app/views/users/new.html.erb
<h2>Login/Sign Up</h2>

<%= render partial: "form" %>